import { create } from "zustand";
const useinvoiceStore = create<InvoiceStore>((set, get) => ({
  jobInfo: {
    Discount: 0,
    OutstandingDues: 0,
    VATAmount: 0,
    CustomerName: "",
    CustomerAddress: "",
    SalesPerson: "",
    PortOfOrigin: "",
    PortOfDestination: "",
    Weight: "",
    Dimensions: "",
    TransitTime: "",
    ShipmentTerms: "",
    CarrierName: "",
    ContainerType: "",
    CustomContainerType: "",
    AirportOfDestination: "",
    AirportOfOrigin: "",
    TypeOfCargo: "",
    isAirinquiry: false,
    CustomerTRN: "",
    Departure: "",
    EstimatedArrival: "",
    CustomerEmail: "",
    CustomerPhoneNo: "",
    FlightInformation: "",
    type: "",
    DriverDetails: "",
    PlaceOfDestination: "",
    PlaceOfOrigin: "",
    RouteDetails: "",
    VehicleDetails: "",
    ShippingLaneDetails: "",
    VesselDetails: "",
    VesselName: "",
    Jobid: "",
    jobInitials: "",
    method: "",
    othershippingDetails: "",
    quotationId: "",
    officeAddress: "",
    blNo: "",
    HAWB: "",
    Movement: "",
    PayableAt: "",
    PlaceOfDelivery: "",
    PlaceOfIssue: "",
    PlaceOfReceipt: "",
    specialInstructions: "",
    termsAndConditions: [""],
    dueDate: "",
    PostingDate: "",
    ShipperAddress: "",
    ShipperName: "",
    ShipperPhone: 0,
    ShippersAccount: "",
    OtherShipperInfo: "",
    ShippersPO: 0,
    ShippersTRN: 0,
    ShipperEmail: "",
  },
  ladleInfo: {
    ConsigneeReference: "",
    CustomerName: "",
    CustomerAddress: "",
    SalesPerson: "",
    PlaceOfOrigin: "",
    PlaceOfDestination: "",
    VesselName: "",
    RouteDetails: "",
    TypeOfCargo: "",
    Weight: "",
    TransitTime: "",
    ShipmentTerms: "",
    CarrierName: "",
    TotalContainers: 0,
    CustomerTRN: "",
    CustomerEmail: "",
    CustomerPhoneNo: "",
    othershippingDetails: "",
    ExportReference: "",
    ForwardingAgent: "",
    PortOfDischarge: "",
    PortOfLoading: "",
    jobInitials: "",
    method: "",
    PlaceOfIssue: "",
    PlaceOfReceipt: "",
    PayableAt: "",
    PlaceOfDelivery: "",
    Movement: "",
    NotifyAddress: "",
    Currency: "",
    Discount: 0,
    Jobid: "",
    OutstandingDues: 0,
    VATAmount: 0,
    specialInstructions: "",
    termsAndConditions: [""],
    officeAddress: "",
    blNo: "",
    Carrier: "",
    CarrierReference: "",
    ContainersReceived: "",
    DateOfIssue: "",
    FreightCollected: "",
    FreightPrepaid: "",
    OriginalBSL: "",
    PackagesReceived: "",
    TotalFreight: "",
    VoyageNo: "",
    ShipperAddress: "",
    ShipperName: "",
    ShipperPhone: 0,
    ShippersAccount: "",
    OtherShipperInfo: "",
    ShippersPO: 0,
    ShippersTRN: 0,
    ShipperEmail: "",
  },
  AirwayInfo: {
    CustomerName: "",
    CustomerAddress: "",
    SalesPerson: "",
    AirportOfOrigin: "",
    AirportOfDestination: "",
    RouteDetails: "",
    TransitTime: "",
    FlightDetails: "",
    ShipmentTerms: "",
    CarrierName: "",
    CustomerTRN: "",
    CustomerAccount: "",
    CustomerEmail: "",
    CustomerPhoneNo: "",
    othershippingDetails: "",
    jobInitials: "",
    method: "",
    Currency: "",
    Flight: "",
    ReferenceNumber: "",
    HandlingInformation: "",
    officeAddress: "",
    Discount: 0,
    AccountingInformation: "",
    PaymentMethod: "",
    RequestedFlight: "",
    Jobid: "",
    OutstandingDues: 0,
    VATAmount: 0,
    specialInstructions: "",
    termsAndConditions: [""],
    AgentsIATA: "",
    AmountInsurance: "",
    CCChargesinDestCurr: "",
    ChargesAtDestination: "",
    ChargesCode: "",
    CollTax: "",
    CollValuation: "",
    CollWeight: "",
    ConsigneesAccount: "",
    CurrConv: "",
    DeclaredValCarriage: "",
    DeclaredValCustoms: "",
    ModeOfPayment: "",
    OtherColl: "",
    OtherPPD: "",
    OtherShipperInfo: "",
    PPDTax: "",
    PPDValuation: "",
    PPDWeight: "",
    SCI: "",
    ShipperAddress: "",
    ShipperName: "",
    ShipperPhone: 0,
    ShippersAccount: "",
    WVColl: "",
    WVPPD: "",
    CollOtherDueAgent: "",
    CollOtherDueCarrier: "",
    PPDOtherDueAgent: "",
    PPDOtherDueCarrier: "",
    IssuingCarriersCity: "",
    IssuingCarriersName: "",
    ShippersPO: 0,
    ShippersTRN: 0,
    Byfirstcarrier: "",
    firstTo: "",
    secondBy: "",
    secondTo: "",
    thirdBy: "",
    thirdTo: "",
    ShipperEmail: "",
  },
  setAirwayBillItems(j) {
    set((state) => {
      return { ...state, AirwayItems: j };
    });
  },
  setAirwayInfo(j) {
    set((state) => ({ ...state, AirwayInfo: j }));
  },
  Items: [],
  AirwayItems: [],
  setInfo(j) {
    set((state) => ({ ...state, jobInfo: j }));
  },
  setItems(j) {
    set((state) => {
      return { ...state, Items: j };
    });
  },
  ladingItems: [],
  setladingItems(j) {
    set((state) => {
      return { ...state, ladingItems: j };
    });
  },
  setladleInfo(j) {
    console.log("Jbn ,", j);
    set((state) => ({ ...state, ladleInfo: j }));
  },
  manifestInfo: {
    officeAddress: "",
    Consolidation: "",
    Date: "",
    Discount: 0,
    Flights: "",
    From: "",
    HeaderAddress: "",
    Jobid: "",
    MAWB: "",
    OutstandingDues: 0,
    To: "",
    Total: "",
    VATAmount: 0,
    specialInstructions: "",
    termsAndConditions: [""],
    ShipperAddress: "",
    ShipperName: "",
    ShipperPhone: 0,
    ShippersAccount: "",
    OtherShipperInfo: "",
    ShippersPO: 0,
    ShippersTRN: 0,
    ShipperEmail: "",
  },
  PODInfo: {
    JobNo: "",
    Description: "",
    Transporter: "",
    Shipper: "",
    DeliveryTo: "",
    ContactPerson: "",
    DeliveryDate: "",
    Time: "",
    ReceiverNameAndSignature: "",
    MobileNumber: "",
    CompanyStamp: "",
    Remarks: "",
    officeAddress: "",
    Discount: 0,
    VATAmount: 0,
    specialInstructions: "",
    termsAndConditions: [""],
    Jobid: "",
    OutstandingDues: 0,
    ShipperAddress: "",
    ShipperName: "",
    ShipperPhone: 0,
    ShippersAccount: "",
    OtherShipperInfo: "",
    ShippersPO: 0,
    ShippersTRN: 0,
    ShipperEmail: "",
    HeaderAddress: "",
  },
  ManifestItems: [],
  PODItems: [],
  setManifestInfo(j) {
    set((state) => ({ ...state, manifestInfo: j }));
  },
  setManifestItems(items) {
    set((state) => ({ ...state, ManifestItems: items }));
  },
  setPODInfo(j) {
    set((state) => ({ ...state, PODInfo: j }));
  },
  setPODItems(items) {
    set((state) => ({ ...state, PODItems: items }));
  },
}));

export default useinvoiceStore;
